services:
  postgres:
    image: postgres:18
    container_name: tms-postgres
    environment:
      POSTGRES_DB: tms-project
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tms-project"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tms-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tms-project
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_FLYWAY_ENABLED: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_DEVTOOLS_RESTART_ENABLED: "false"
      SPRING_DEVTOOLS_LIVERELOAD_ENABLED: "false"
    ports:
      - "8080:8080"
