spring.application.name=tms

spring.datasource.url=jdbc:postgresql://localhost:5433/tms-project
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# flyway configuration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JSP configuration
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

# DevTools configuration
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
