-- 1. Configuration Tables (Templates)
CREATE TABLE IF NOT EXISTS ticket_status (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    hex_color VARCHAR(7),
    is_default BOOLEAN DEFAULT FALSE,
    is_finalizer BOOLEAN DEFAULT FALSE,
    -- Auditoria
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ,
    created_by VARCHAR(100),
    updated_by VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS ticket_type (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    deadline_days INTEGER NOT NULL,
    -- Auditoria
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ,
    created_by VARCHAR(100),
    updated_by VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS block (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    street VARCHAR(100),
    number INTEGER,
    floor_count INTEGER,
    units_per_floor INTEGER,
    -- Auditoria
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ,
    created_by VARCHAR(100),
    updated_by VARCHAR(100)
);

-- 2. User and Infrastructure
CREATE TABLE IF NOT EXISTS user_account (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    username VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL,
    role VARCHAR(50) NOT NULL, -- ROLE_ADMIN, ROLE_RESIDENT, ROLE_STAFF
    -- Auditoria
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ,
    created_by VARCHAR(100),
    updated_by VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS unit (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number INTEGER NOT NULL,
    floor_number INTEGER,
    block_id BIGINT NOT NULL,
    -- Auditoria
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ,
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    CONSTRAINT fk_unit_block FOREIGN KEY (block_id) 
        REFERENCES block(id) ON UPDATE CASCADE ON DELETE RESTRICT
);

-- 3. Junction Tables (Many-to-Many)
CREATE TABLE IF NOT EXISTS resident_unit (
    user_id BIGINT NOT NULL,
    unit_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, unit_id),
    CONSTRAINT fk_resident_user FOREIGN KEY (user_id) 
        REFERENCES user_account(id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_resident_unit FOREIGN KEY (unit_id) 
        REFERENCES unit(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS collaborator_ticket_type (
    user_id BIGINT NOT NULL,
    ticket_type_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, ticket_type_id),
    CONSTRAINT fk_collaboration_user FOREIGN KEY (user_id) 
        REFERENCES user_account(id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_collaboration_type FOREIGN KEY (ticket_type_id) 
        REFERENCES ticket_type(id) ON UPDATE CASCADE ON DELETE CASCADE
);

-- 4. Ticket Management
CREATE TABLE IF NOT EXISTS ticket (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    description VARCHAR(300),
    status_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    unit_id BIGINT NOT NULL,
    ticket_type_id BIGINT NOT NULL,
    completed_at TIMESTAMPTZ,
    due_date TIMESTAMPTZ,
    -- Auditoria
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ,
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    CONSTRAINT fk_ticket_status FOREIGN KEY (status_id) REFERENCES ticket_status(id),
    CONSTRAINT fk_ticket_author FOREIGN KEY (author_id) REFERENCES user_account(id),
    CONSTRAINT fk_ticket_unit FOREIGN KEY (unit_id) REFERENCES unit(id),
    CONSTRAINT fk_ticket_type FOREIGN KEY (ticket_type_id) REFERENCES ticket_type(id)
);

-- 5. Interactions
CREATE TABLE IF NOT EXISTS comment (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description TEXT NOT NULL,
    ticket_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    -- Auditoria
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ,
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    CONSTRAINT fk_comment_ticket FOREIGN KEY (ticket_id) 
        REFERENCES ticket(id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_comment_author FOREIGN KEY (author_id) 
        REFERENCES user_account(id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS attachment (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name VARCHAR(255) NOT NULL,
    mime_type VARCHAR(50),
    storage_path VARCHAR(255) NOT NULL,
    ticket_id BIGINT NOT NULL,
    -- Auditoria
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMPTZ,
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    CONSTRAINT fk_attachment_ticket FOREIGN KEY (ticket_id) 
        REFERENCES ticket(id) ON UPDATE CASCADE ON DELETE CASCADE
);